import sys
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pathlib import Path

ROOT = Path(__file__).parent.parent.resolve()
sys.path.insert(0, str(ROOT))

from backend.core.job_manager import Job
from backend.core.pipeline import run_pipeline
import asyncio

async def generate_and_plot(prompt, output_image_path):
    job = Job("test_visual_001", prompt)
    print(f"Running pipeline for: {prompt}")
    await run_pipeline(job)
    
    if job.error:
        print(f"Failed: {job.error}")
        return
        
    rooms = job.preview
    if not rooms:
        print("No rooms generated.")
        return

    # Extract raw room dicts generated by the GNN
    # Note: job.preview holds the summary dicts, but we need x, y, width, height. 
    # Let's import the GNN adapter to generate raw rooms directly for plotting.
    from backend.core.real_gnn import get_real_gnn
    from backend.core.spec_converter import normalise_spec
    from backend.core.nlp_adapter import get_nlp_adapter
    
    # We will just run the model and Layer 3 directly to get the dictionaries with x, y, width, height
    nlp = get_nlp_adapter()
    raw_spec = nlp.parse(prompt)
    spec = normalise_spec(raw_spec)
    
    gnn = get_real_gnn()
    room_graph = gnn.generate(spec)
    
    from backend.core.pipeline import _validate_and_fix
    room_graph = _validate_and_fix(room_graph, spec)
    
    raw_rooms = room_graph["rooms"]

    fig, ax = plt.subplots(figsize=(10, 8))
    
    # Assign colors to room types
    import matplotlib.cm as cm
    types = list(set([r['type'] for r in raw_rooms]))
    color_map = {t: cm.tab20(i / len(types)) for i, t in enumerate(types)}

    max_x, max_y = 0, 0
    min_x, min_y = float('inf'), float('inf')

    for r in raw_rooms:
        x, y, w, h = r['x'], r['y'], r['width'], r['height']
        rtype = r['type']
        
        rect = patches.Rectangle((x, y), w, h, linewidth=2, edgecolor='black', facecolor=color_map[rtype], alpha=0.6)
        ax.add_patch(rect)
        
        # Room label
        ax.text(x + w/2, y + h/2, f"{rtype.title()}\n{r['area']}m²", 
                ha='center', va='center', fontsize=9, weight='bold', color='black')
        
        max_x = max(max_x, x + w)
        max_y = max(max_y, y + h)
        min_x = min(min_x, x)
        min_y = min(min_y, y)

    # Add 10% padding
    pad_x = (max_x - min_x) * 0.1
    pad_y = (max_y - min_y) * 0.1
    
    ax.set_xlim(min_x - pad_x, max_x + pad_x)
    ax.set_ylim(min_y - pad_y, max_y + pad_y)
    
    ax.set_aspect('equal')
    ax.grid(True, linestyle='--', alpha=0.5)
    plt.title(f"2D AI Floorplan\\n'{prompt}'")
    plt.xlabel("Meters")
    plt.ylabel("Meters")
    
    plt.savefig(output_image_path, dpi=200, bbox_inches='tight')
    print(f"\\n✅ Saved 2D visual layout to: {output_image_path}")

if __name__ == "__main__":
    prompt = "A warm cozy house with 2 bedrooms, a big living room, an open kitchen, and a small garden"
    
    output_path = ROOT / "output" / "api_generated" / "2d_preview.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    asyncio.run(generate_and_plot(prompt, str(output_path)))
